version: "3.3"
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    deploy:
      replicas: 3
      resources:
        limits:
          cpu: '0.1'
          memory: 50M
      restart_policy:
        condition: on-failure
